name: camionesm
description: "Proyecto Logistico"

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

linter:
  rules:
    - use_super_parameters

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  font_awesome_flutter: ^10.7.0
  reactive_forms: ^17.0.1
  intl_phone_field: ^3.2.0
  get: ^4.6.6
  intl: ^0.19.0
  http: ^1.2.2
  url_launcher: ^6.3.0
  table_calendar: ^3.1.2
  shimmer: ^3.0.0
  animated_bottom_navigation_bar: ^1.3.3
  dotted_border: ^2.1.0
  timelines: ^0.1.0
  fl_chart: ^0.68.0
  carousel_slider: ^4.2.1
  file_picker: ^8.1.1
  pdfx: ^2.6.0
  image_picker: ^1.1.2
  flutter_map: ^6.2.1
  flutter_map_marker_cluster: ^1.3.6
  latlong2: ^0.9.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: "^0.11.0"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/files/json/
